import { ServiceCategory } from "@/components/sections/services/ServicesContent";

export const FALLBACK_CATEGORIES: ServiceCategory[] = [
  {
    _id: "serviceCategory-womens-hair",
    title: "Hair Masterclass",
    slug: "hair-masterclass",
    gender: "womens",
    displayOrder: 1,
    items: [
      { name: "U Cut", price: "₹400" },
      { name: "V Cut", price: "₹400" },
      { name: "Straight Cut", price: "₹400" },
      { name: "Advance Hair Cut", price: "₹800" },
      { name: "Kid Cut", price: "₹400" },
      { name: "Head Massage", price: "₹300" },
      { name: "Shampoo + Conditioning + Blast Dry", price: "₹350" },
      { name: "Blow Dry", price: "₹450" },
      { name: "Iron Curls", price: "from ₹650" },
      { name: "Tong Curls", price: "from ₹1000" },
      { name: "Root Touch Up (Ammonia Free)", price: "₹1200" },
      { name: "Global Colour (Ammonia Free)", price: "from ₹2200" },
      { name: "Global Highlights", price: "S: ₹2,000 / M: ₹2,500 / L: ₹3,500" },
      { name: "Crown Highlights", price: "from ₹1500" },
      { name: "Funk's (1 Foil)", price: "from ₹350" },
      { name: "Smoothening S/M/L", price: "from ₹4.5k" },
      { name: "Rebonding S/M/L", price: "from ₹4.5k" },
      { name: "Keratin S/M/L", price: "from ₹5.5k" },
      { name: "Dry Hair Spa", price: "from ₹1000" },
      { name: "Smooth Straight Hair Spa", price: "from ₹1400" },
      { name: "Hair Fall Control Spa", price: "from ₹1500" },
      { name: "Frizz Control", price: "from ₹1200" },
      { name: "Repair & Rejuvenate", price: "from ₹1500" },
      { name: "Anti Hair Fall Treatment", price: "from ₹1400" },
      { name: "Anti-Dandruff Treatment", price: "from ₹1500" },
      { name: "Keratin Spa Treatment", price: "from ₹2000" },
    ],
  },
  {
    _id: "serviceCategory-womens-skin",
    title: "Skin Rituals",
    slug: "skin-rituals",
    gender: "womens",
    displayOrder: 2,
    items: [
      { name: "Full Arms (Normal / Chocolate / Rica)", price: "₹250 / ₹400 / ₹650" },
      { name: "Full Legs (Normal / Chocolate / Rica)", price: "₹600 / ₹700 / ₹1400" },
      { name: "Half Legs (Normal / Chocolate / Rica)", price: "₹300 / ₹350 / ₹700" },
      { name: "Under Arms (Normal / Chocolate / Rica)", price: "₹100 / ₹150 / ₹250" },
      { name: "Full Face (Normal / Chocolate)", price: "₹100 / ₹200" },
      { name: "Upper Lip (Normal / Chocolate)", price: "₹50 / ₹70" },
      { name: "Chin (Normal / Chocolate)", price: "₹40 / ₹50" },
      { name: "Full Body Waxing (Normal / Choc / Rica)", price: "from ₹1000" },
      { name: "D-Tan Face & Neck", price: "₹600" },
      { name: "D-Tan Face & Neck Blouse Line", price: "₹800" },
      { name: "D-Tan Full Arms", price: "₹800" },
      { name: "D-Tan Full Legs", price: "₹1000" },
      { name: "D-Tan Half Arms", price: "₹400" },
      { name: "D-Tan Half Legs", price: "₹500" },
      { name: "D-Tan Full Back/Front", price: "₹1000" },
      { name: "Clean Up", price: "₹500" },
      { name: "Fruit Facial", price: "₹800" },
      { name: "Pearl Facial", price: "₹1400" },
      { name: "Gold Facial", price: "₹1800" },
      { name: "Silver Facial", price: "₹1400" },
      { name: "Diamond Facial", price: "₹1500" },
      { name: "Skin Whitening Facial", price: "₹2200" },
      { name: "Skin Tightening", price: "₹1800" },
      { name: "Shahnaz Diamond", price: "₹2200" },
      { name: "Shahnaz Gold", price: "₹2400" },
      { name: "Glovite Facial", price: "₹2800" },
      { name: "Oxy Blast Facial", price: "₹2100" },
      { name: "Tan Clear Facial", price: "₹2300" },
      { name: "Sensi Glow Facial", price: "₹2800" },
      { name: "Clari Glow Facial", price: "₹3000" },
      { name: "O2C2 Facial", price: "₹4000" },
      { name: "O3+ D Tan Clean Up", price: "₹1000" },
      { name: "O3+ Pore & Purifying Cleanup", price: "₹1100" },
      { name: "O3+ Whitening & Hydra Facial", price: "₹3000" },
      { name: "O3+ Purifying & Detox Facial", price: "₹2200" },
      { name: "O3+ Bridal Facial", price: "₹4000" },
      { name: "Protein Peel", price: "₹1500" },
      { name: "Acne & Blackhead Control Peel", price: "₹1800" },
      { name: "Lightning Peel", price: "₹1700" },
      { name: "Shine & Luminous Glow Peel", price: "₹1800" },
      { name: "Glow Active Procedure Peel", price: "₹2200" },
      { name: "O3+ Luxury Pedicure", price: "₹1500" },
      { name: "Basic Pedicure", price: "₹800" },
      { name: "Basic Manicure", price: "₹500" },
      { name: "Mini Pedicure", price: "₹1300" },
      { name: "Mini Manicure", price: "₹1000" },
      { name: "Crystal Spa Pedicure", price: "₹1300" },
      { name: "Crystal Spa Manicure", price: "₹950" },
      { name: "Full Body Scrub", price: "₹1200" },
      { name: "Full Body Coco Butter Massage", price: "₹1500" },
      { name: "Full Body D-Tan Removal", price: "₹3500" },
    ],
  },
  {
    _id: "serviceCategory-womens-refinement",
    title: "Refinement",
    slug: "refinement",
    gender: "womens",
    displayOrder: 3,
    items: [
      { name: "Eyebrow Threading", price: "₹50" },
      { name: "Upper Lip Threading", price: "₹40" },
      { name: "Forehead Threading", price: "₹50" },
      { name: "Chin Threading", price: "₹50" },
      { name: "Full Face Threading", price: "₹200" },
      { name: "Neck Threading", price: "₹70" },
      { name: "Side Locks Threading", price: "₹70" },
      { name: "Face Bleach (Oxy)", price: "₹350" },
      { name: "Neck Bleach", price: "₹250" },
      { name: "Gold Face Bleach", price: "₹500" },
      { name: "Blouse Line Bleach", price: "₹350" },
      { name: "Stomach Bleach", price: "₹500" },
      { name: "Underarms Bleach", price: "₹150" },
      { name: "Full Arm Bleach", price: "₹600" },
      { name: "Half Arm Bleach", price: "₹350" },
      { name: "Half Leg Bleach", price: "₹500" },
      { name: "Full Leg Bleach", price: "₹1000" },
      { name: "Full Back / Front Bleach", price: "₹600 / ₹800" },
      { name: "Full Body Bleach", price: "₹2000" },
    ],
  },
  {
    _id: "serviceCategory-bridal",
    title: "Bridal Studio",
    slug: "bridal-studio",
    gender: "bridal",
    displayOrder: 1,
    items: [
      { name: "Party Makeup", price: "₹1500" },
      { name: "Saree Draping", price: "₹500 / ₹400" },
      { name: "Hair Style", price: "₹600 / ₹1000 / ₹2000" },
      { name: "Reception Bridal Makeup (HD)", price: "₹15000", isHighlighted: true },
      { name: "Wedding Bridal Makeup HD", price: "₹15000", isHighlighted: true },
      { name: "Eng / Mehndi / Sangeet / Haldi (HD)", price: "₹10000" },
      { name: "Reception Bridal Makeup (Non-HD)", price: "₹10000" },
      { name: "Wedding Bridal Makeup (Non-HD)", price: "₹10000" },
      { name: "Eng / Mehndi / Sangeet / Haldi (Non-HD)", price: "₹8000" },
      { name: "Baby Shower Makeup", price: "₹4000" },
      { name: "Model Make-up", price: "₹4000" },
      { name: "Gel Polish", price: "₹850" },
      { name: "Fake Nails + Gel Polish", price: "₹1050" },
      { name: "Nail Extensions / Acrylic Gel Polish", price: "₹2500" },
      { name: "Nail Polish Removal", price: "₹250" },
    ],
  },
  {
    _id: "serviceCategory-mens-hair",
    title: "Men's Grooming",
    slug: "mens-grooming",
    gender: "mens",
    displayOrder: 1,
    items: [
      { name: "Haircut", price: "₹200" },
      { name: "Advanced Haircut", price: "₹250" },
      { name: "Clean Shave", price: "₹100" },
      { name: "Beard Styling", price: "₹100" },
      { name: "Hair Wash Styling", price: "₹150" },
      { name: "Kid Little Champs", price: "₹200" },
      { name: "Head Massage (Parachute)", price: "₹150" },
      { name: "Herbal Oil Massage", price: "₹150" },
      { name: "Olive & Almond Oil Massage", price: "₹250" },
      { name: "Global Hair Colour", price: "₹500" },
      { name: "Global Hair Colour (Ammonia Free)", price: "₹500" },
      { name: "Fashion Highlights Per Streak", price: "₹150" },
      { name: "Fashion Global Highlights", price: "₹600" },
      { name: "Beard Colour", price: "₹300" },
      { name: "Classic Hair Spa", price: "₹800" },
      { name: "Dry & Frizzy Control Spa", price: "₹1200" },
      { name: "Keratin Hair Spa", price: "₹500" },
      { name: "Anti Hair Fall Treatment", price: "₹1500" },
      { name: "Anti Dandruff Treatment", price: "₹1500" },
      { name: "Hair Smoothening", price: "from ₹1500" },
      { name: "Hair Keratin", price: "from ₹3000" },
    ],
  },
  {
    _id: "serviceCategory-mens-skin",
    title: "Men's Skin",
    slug: "mens-skin",
    gender: "mens",
    displayOrder: 2,
    items: [
      { name: "Peel Off Mask", price: "₹600" },
      { name: "Hydra Rejuvenate Mask", price: "₹5000" },
      { name: "O3+ Rejuvenate Mask", price: "₹2000" },
      { name: "Pedicure", price: "₹600" },
      { name: "Spa Pedicure", price: "₹1200" },
      { name: "D-Tan Pedicure", price: "₹1000" },
      { name: "Manicure", price: "₹600" },
      { name: "Spa Manicure", price: "₹1000" },
      { name: "D-Tan Manicure", price: "₹1250" },
      { name: "Nail Cut & Filling", price: "₹150" },
      { name: "D-Tan Face & Neck", price: "₹450" },
      { name: "D-Tan Raaga & O3+", price: "₹800" },
      { name: "D-Tan Full Hands", price: "₹1500" },
      { name: "D-Tan Full Body", price: "₹3000" },
      { name: "Body Polishing", price: "₹5000" },
      { name: "Basic Cleanup", price: "₹400" },
      { name: "Lotus Cleanup", price: "₹1000" },
      { name: "O3+ Cleanup", price: "₹1300" },
      { name: "Raaga Cleanup", price: "₹700" },
      { name: "Fruit Facial", price: "₹800" },
      { name: "Pearl Facial", price: "₹1500" },
      { name: "Gold Facial", price: "₹1800" },
      { name: "Diamond Facial", price: "₹1800" },
      { name: "Skin Whitening", price: "₹1700" },
      { name: "Anti Ageing Facial", price: "₹1800" },
      { name: "Cheryl's Oxy Blast", price: "₹3000" },
      { name: "Cheryl's D-Tan Facial", price: "₹3000" },
      { name: "O3+ Facial", price: "₹3500" },
      { name: "Party Makeup", price: "₹3500" },
      { name: "Groom Makeup", price: "₹5000", isHighlighted: true },
      { name: "Trial Makeup", price: "₹2000" },
    ],
  },
  {
    _id: "serviceCategory-tattoo",
    title: "Tattoo Artistry",
    slug: "tattoo-artistry",
    gender: "tattoo",
    displayOrder: 1,
    items: [
      { name: "Fine-Line Tattoo (Small)", price: "from ₹500" },
      { name: "Fine-Line Tattoo (Large)", price: "from ₹4000" },
      { name: "Realism Tattoo", price: "from ₹3000" },
      { name: "Cover-Up Tattoo", price: "from ₹5000" },
      { name: "Touch-Up Session", price: "₹800" },
      { name: "Custom Design Consultation", price: "Free", isHighlighted: true },
      { name: "Ear Piercing", price: "₹500" },
    ],
  },
];
