import { defineField, defineType } from "sanity";

export const homePage = defineType({
  name: "homePage",
  title: "🏠 Home Page",
  type: "document",
  groups: [
    { name: "hero",      title: "🎬 Hero Section",           default: true },
    { name: "stats",     title: "📊 Stats Strip"                          },
    { name: "services",  title: "💇 Service Grid Images"                  },
    { name: "transform", title: "🔁 Before & After Slider"               },
  ],
  fields: [
    // ── HERO ─────────────────────────────────────────────────────────────
    defineField({
      name: "heroEyebrow",
      title: "Hero Small Label (above headline)",
      type: "string",
      group: "hero",
      description: 'Small uppercase text shown above the main headline. e.g. "The Premium Experience"',
      initialValue: "Hyderabad's premium family salon for hair, skin, bridal & tattoo artistry",
    }),
    defineField({
      name: "heroHeadline",
      title: "Hero Headline — Normal Text",
      type: "string",
      group: "hero",
      description: 'First line of the big heading. e.g. "Walk in."',
      initialValue: "Walk in.",
    }),
    defineField({
      name: "heroHeadlineItalic",
      title: "Hero Headline — Italic Text",
      type: "string",
      group: "hero",
      description: 'Second line of the big heading, displayed in italic. e.g. "Walk out different."',
      initialValue: "Walk out different.",
    }),
    defineField({
      name: "heroCtaText",
      title: "Hero Button Label",
      type: "string",
      group: "hero",
      description: 'Text on the main call-to-action button. e.g. "Reserve Your Time" or "Book Your Appointment"',
      initialValue: "Book Your Appointment",
    }),
    defineField({
      name: "heroBackgroundImage",
      title: "Hero Background Photo",
      type: "image",
      group: "hero",
      options: { hotspot: true },
      description: "📸 HERO BACKGROUND — fills the entire screen on load. Required Size: exactly 1920 × 1080 px (16:9). Max file size: 500KB. Format: WEBP (or JPG). 📱 MOBILE FIRST: Ensure the subject is centred so it crops well on mobile screens automatically.",
      fields: [
        defineField({
          name: "alt",
          title: "Image Description",
          type: "string",
          description: 'e.g. "Stylist doing a bridal hairstyle at Root\'s The Family Salon"',
        }),
      ],
    }),


    // ── STATS ─────────────────────────────────────────────────────────────
    defineField({
      name: "statYears",
      title: "Years in Business",
      type: "number",
      group: "stats",
      description: "Displayed in the stats strip on the homepage. Just enter the number, e.g. 8",
      initialValue: 8,
    }),
    defineField({
      name: "statRating",
      title: "Google Rating",
      type: "number",
      group: "stats",
      description: "Your star rating out of 5. e.g. 4.8",
      initialValue: 4.8,
    }),
    defineField({
      name: "statLocations",
      title: "Number of Branches",
      type: "number",
      group: "stats",
      description: "How many active branch locations you have. e.g. 2",
      initialValue: 2,
    }),
    defineField({
      name: "statReviews",
      title: "Total Reviews (in thousands)",
      type: "number",
      group: "stats",
      description: "Enter the number in thousands. e.g. enter 1.6 to display 1.6K reviews.",
      initialValue: 1.6,
    }),

    // ── SERVICE GRID IMAGES ───────────────────────────────────────────────
    defineField({
      name: "servicesHeadline",
      title: "Services Section Headline",
      type: "string",
      group: "services",
      description: 'e.g. "Curated Services"',
      initialValue: "Curated Services",
    }),
    defineField({
      name: "servicesSubheadline",
      title: "Services Section Subheadline",
      type: "text",
      group: "services",
    }),
    defineField({
      name: "hairServiceImage",
      title: "Hair — Grid Card Photo",
      type: "image",
      group: "services",
      options: { hotspot: true },
      description: "📸 HOME PAGE — Hair card in the Services Grid. Required Size: exactly 600 × 800 px (3:4 portrait). Max file size: 300KB. Format: WEBP (preferred) or JPG. 📱 Crops from centre on mobile — keep the subject centered.",
    }),
    defineField({
      name: "bridalServiceImage",
      title: "Bridal — Grid Card Photo",
      type: "image",
      group: "services",
      options: { hotspot: true },
      description: "📸 HOME PAGE — Bridal card in the Services Grid. Required Size: exactly 600 × 800 px (3:4 portrait). Max file size: 300KB. Format: WEBP or JPG. 📱 Keep the subject (face/hair) centred for mobile.",
    }),
    defineField({
      name: "skinServiceImage",
      title: "Skin — Grid Card Photo",
      type: "image",
      group: "services",
      options: { hotspot: true },
      description: "📸 HOME PAGE — Skin card in the Services Grid. Required Size: exactly 600 × 800 px (3:4 portrait). Max file size: 300KB. Format: WEBP or JPG. 📱 Close-up facial or treatment photos work best (keep focal point centered).",
    }),
    defineField({
      name: "tattooServiceImage",
      title: "Tattoo — Grid Card Photo",
      type: "image",
      group: "services",
      options: { hotspot: true },
      description: "📸 HOME PAGE — Tattoo card in the Services Grid. Required Size: exactly 600 × 800 px (3:4 portrait). Max file size: 300KB. Format: WEBP or JPG. 📱 Ensure the focal point is centered for mobile displays.",
    }),
    defineField({
      name: "nailsServiceImage",
      title: "Nails — Grid Card Photo",
      type: "image",
      group: "services",
      options: { hotspot: true },
      description: "📸 HOME PAGE — Nails card in the Services Grid. Required Size: exactly 600 × 800 px (3:4 portrait). Max file size: 300KB. Format: WEBP or JPG.",
    }),
    defineField({
      name: "piercingServiceImage",
      title: "Piercing — Grid Card Photo",
      type: "image",
      group: "services",
      options: { hotspot: true },
      description: "📸 HOME PAGE — Piercing card in the Services Grid. Required Size: exactly 600 × 800 px (3:4 portrait). Max file size: 300KB. Format: WEBP or JPG.",
    }),

    // ── BEFORE & AFTER ────────────────────────────────────────────────────
    defineField({
      name: "transformationsHeadline",
      title: "Before & After Headline",
      type: "string",
      group: "transform",
      description: 'e.g. "Visible Transformations"',
      initialValue: "Visible Transformations",
    }),
    defineField({
      name: "transformationsSubheadline",
      title: "Before & After Subheadline",
      type: "text",
      group: "transform",
    }),
    defineField({
      name: "beforeAfterHairBefore",
      title: "Hair Transformation — BEFORE Photo",
      type: "image",
      group: "transform",
      options: { hotspot: true },
      description: "📸 HOME PAGE — Before/After Slider, hair BEFORE photo (left side). Required Size: exactly 800 × 800 px (Square 1:1) OR exactly 800 × 1000 px (Portrait 4:5). Max file size: 300KB. Format: WEBP or JPG. ⚠️ The BEFORE and AFTER photos must be identical in size to prevent slider misalignment.",
    }),
    defineField({
      name: "beforeAfterHairAfter",
      title: "Hair Transformation — AFTER Photo",
      type: "image",
      group: "transform",
      options: { hotspot: true },
      description: "📸 HOME PAGE — Before/After Slider, hair AFTER photo (right side). Required Size: must exactly match the BEFORE photo (800 × 800 px or 800 × 1000 px). Max file size: 300KB. Format: WEBP or JPG.",
    }),
    defineField({
      name: "beforeAfterSkinBefore",
      title: "Skin Transformation — BEFORE Photo",
      type: "image",
      group: "transform",
      options: { hotspot: true },
      description: "📸 HOME PAGE — Before/After Slider, skin BEFORE photo (left side). Required Size: exactly 800 × 800 px (Square 1:1) OR exactly 800 × 1000 px (Portrait 4:5). Max file size: 300KB. Format: WEBP or JPG. ⚠️ Must be identical in size to the AFTER photo to prevent slider bugs.",
    }),
    defineField({
      name: "beforeAfterSkinAfter",
      title: "Skin Transformation — AFTER Photo",
      type: "image",
      group: "transform",
      options: { hotspot: true },
      description: "📸 HOME PAGE — Before/After Slider, skin AFTER photo (right side). Required Size: must exactly match the BEFORE photo. Max file size: 300KB. Format: WEBP or JPG.",
    }),
    // ── CTA ───────────────────────────────────────────────────────────────
    defineField({
      name: 'ctaHeadline',
      title: 'Bottom CTA Headline',
      type: 'string',
      description: 'e.g. "Ready for your Look?"',
    }),
    defineField({
      name: 'ctaButtonText',
      title: 'Bottom CTA Button Text',
      type: 'string',
      description: 'e.g. "Book Consultation via WhatsApp"',
    }),
  ],
  preview: {
    select: { media: "heroBackgroundImage" },
    prepare({ media }) {
      return { title: "🏠 Home Page", subtitle: "Edit homepage content & photos", media };
    },
  },
});
